name: Build and Deploy to Harbor (Dev + Staging)

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches: 
      - dev
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      HARBOR_REGISTRY: ${{ vars.HARBOR_REGISTRY }}
      IMAGE_TAG: ${{ github.ref == 'refs/heads/dev' && 'dev' || 'latest' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.HARBOR_REGISTRY }}/${{ vars.HARBOR_PROJECT }}/ydt-api:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
